# Generated by Django 5.2.3 on 2025-08-14 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliolink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portfoliolink',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbs/'),
        ),
        migrations.AlterField(
            model_name='portfoliolink',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='portfoliolink',
            index=models.Index(fields=['owner', '-created_at'], name='portfolio_p_owner_i_6dcebf_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfoliolink',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='portfolio_owner_slug_unique'),
        ),
    ]
