# Generated by Django 5.2.3 on 2025-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('backend', 'Backend Development'), ('frontend', 'Frontend Development'), ('fullstack', 'Full-Stack Development'), ('data', 'Data Science / AI'), ('devops', 'DevOps / Infrastructure'), ('qa', 'QA / Testing'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
