# Generated by Django 5.2.3 on 2025-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_message_reply_to_alter_message_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
