# Generated by Django 5.2.3 on 2025-08-11 18:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_archived_field'),
    ]

    operations = [
        RunSQL(
            sql=(
                "ALTER TABLE messaging_message "
                "DROP COLUMN IF EXISTS archived;"
            ),
            reverse_sql=""
        ),
        
        migrations.AddField(
            model_name='message',
            name='archived_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='archived_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(
                upload_to='message_attachments/',
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage()
            ),
        ),
    ]
